before_script: ./configure
branches:
  only:
    - master
notifications:
  recipients:
    - evan+notify@phx.io
    - bford@engineyard.com
    - d.bussink@gmail.com
  email:
    on_success: change
    on_failure: always
  webhooks: http://elle.fallingsnow.net:13424/
