language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm38 && brew install openssl && brew link --force --overwrite llvm38; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./build.sh --llvm-config=llvm-config --cc=clang --cxx=clang++; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./build.sh --with-include-dir=$OPENSSL_DIR/include --with-lib-dir=$OPENSSL_DIR/lib --llvm-config=llvm-config-3.8 --cc=clang-3.8 --cxx=clang++-3.8; fi
after_success:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build_support.sh archive_codedb; fi
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then ./scripts/deploy.sh release github website triggers; fi
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#rubinius
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      secure: h2oTAbAZF6+c6iv/kHoDGtl1mzQDF2vQSKWnO1pwfEz+L80lX9u3+JB+jsbYUcZ9smBRnRRghqxpLBmyzH3QZCrBdxKnTWfGc7I7lkTCFQZ5O3pPmIusO6W5zX+YUc+NHPPZXouHuHFmEeEB9vJnt/YB/fyGAGOIq+qXV4s+R9M=
    on_success: always
    on_failure: always
    on_start: always
env:
  global:
  - OPENSSL_DIR=$(brew --prefix openssl)
  - RBXOPT=-Xcodedb.cache.enabled=no
  - LANG="en_US.UTF-8"
  - secure: olbok/GN6rOYvPnHBYWGz7giCoCdLFpT/7WSBHukYO3E0uNeqAUOOgW2BFOwCVWdSEJ/iTvJXZQ4qVZHX+6jRfvILZeGv+D2P93VdD8UFQRoTOfFC7esAo525s9fuKm9ehUGWZxlzGOBHHckky1jn6pEf8mlXAVM5e76dlH0fck=
  - secure: aqG9eB/PrzQ7XJQN6YX/00sNVvwSB77saxXQzguL2WFjAXB74h6168Hzq+awHtNX/vfOb6ta7fpWLHrA0D+gmZnvTR29VlP6nd0vs1tkdX1/jWbiBHjamRffp+NWVdKbJKYn5iLOGXcuUMOzY/opLKOdvxKZfkxGMxR2tTNLZUE=
  - secure: NaiH/2wYgzWT3xcscU6Bzw1Zd9lZYPG6OkCRZcQcIXZXwQTmZrGTcZfy5fDe2Vzotvwfr+2B4Ko6axE3KFrsmjTIVD/lI44Y3K+UFHOKhrm6niVtMD6Rx/oUO30hoB3/OkmZnI578F4M5y7x17sDei4L0NKPgnUhm0P0/WPCze4=
